### ISSUE TITLE
dict.txt in generation model and translation model

### ISSUE THREAD

**Issue by ever4244** [microsoft/Unicoder#5]
Good Morning!
I am sorry that I met some issues that need further clarification.

Q1:
I want to know how is your dict.txt is generated and used in the fairseq-preprocess

dict.txt in your pre-trained model 
(
generation model:
https://onedrive.live.com/?authkey=%21AOkzIYo8pYONMb4&id=5C2C1309D09F7C6B%212278&cid=5C2C1309D09F7C6B
understanding model:
https://onedrive.live.com/?authkey=%21AHp7WdcNCamlkVw&id=5C2C1309D09F7C6B%212249&cid=5C2C1309D09F7C6B
):
```
, 1
. 1
▁ 1
s 1
▁de 1
- 1
▁a 1
a 1
: 1
e 1
i 1
▁( 1
) 1
▁i 1
t 1
n 1
▁- 1
▁la 1
▁en 1
▁in 1
▁na 1
' 1
’ 1
... 1
▁e 1
▁на 1
。 1
o 1
? 1
en 1
```

The second column is always 1.  

However when I following the prepare-iwslt17-multilingual.sh
https://github.com/pytorch/fairseq/tree/master/examples/translation
The dictionary I get by fairseq-preprocess is like this:

```
▁the 3488934
, 2538615
. 1863447
▁of 1773456
▁to 1645036
▁and 1395057
▁in 1078123
▁that 856757
▁is 824487
▁a 817413
▁for 556440
▁I 542653
▁on 487723
▁be 442718
▁this 439733
▁we 424269
▁are 365974
▁have 348747
▁it 345349
▁not 332216
▁as 317747
▁with 311021
▁which 303192
▁European 285795
▁The 261132
▁will 256812
▁by 254216
- 243721
▁has 227060
s 195653
```

The second column is the frequency of the tokens.  

So how to generate the dict.txt for your model? why does the frequency of tokens are all 1 (I assume you also generate the dict.txt by fairseq-preprocess)?

BTW: It seems to me the default fairseq example all use fastBPE instead of sentencepiece model.  In fastBPE you can obtain a vocab file when you learn the BPE dictionary, so you can provide this vocab.txt to fairseq-preprocess, because the vocab file is also the token and the token frequency format. In this way, you can always get a unified joint dictionary for all the languages by letting setting --tgtdict = vocab:

fairseq-preprocess --source-lang $src --target-lang $tgt \
         --trainpref $bpe/train.$src-$tgt \
         --joined-dictionary **_--tgtdict $bpe/vocab_** \
         --destdir $data_bin \
         --workers 40

However, the sentencepiece.bpe.vocab learned by sentencepiece is different from vocab learned by fastBPE. sentencepiece.bpe.vocab is like:

```
<unk>	0
<s>	0
</s>	0
en	-0
▁d	-1
er	-2
es	-3
on	-4
▁a	-5
in	-6
▁p	-7
▁l	-8
▁s	-9
▁c	-10
ti	-11
▁t	-12
re	-13
▁de	-14
is	-15
```
where the second column is actually the negative id index instead of frequency, so it can not be provided for fairseq-preprocess as input for **--tgtdict** .   So I am wondering: 

1.  How you get your dict.txt (as sentencepiece do not automatically produce such file, while fastBPE does produce similar file but the second column is frequency rather than 1)
2.  How do you relate this dict.txt with fairseq-preprocess when binarization the training text? Do you provide dict.txt as input for **--tgtdict** as an unified joined dictionary for all the languages?

Q2:
As I mentioned earlier:
```
I see that in the "generation" folder the unicoder X_dae model is fairseq based.
In the "understanding" folder, the pre-trained model is huggings transformer-based.
It seems to me that the fairseq trained model is xxx.pt while the huggings transformer-based model is saved as pytorch_model.bin and config.json. So I am puzzled about how to use one encoder for generation and understanding tasks.

```
Is it correct that I need to train a Roberta model in fairseq first then use the conversion code (https://github.com/huggingface/transformers/blob/master/src/transformers/models/roberta/convert_roberta_original_pytorch_checkpoint_to_pytorch.py) to convert it to transformer format?

**Comment by Eureka6174** [comment]
1. I just reused the dictionary from XLM Roberta and I did try to rebuild a dictionary.
2. For all languages, I used the same dictionary.
3. I think the Roberta model could match the convert scripts. If you are training other models, you need to find a different scripts or write one by yourself.

**Comment by Eureka6174** [comment]
No further questions.
