### ISSUE TITLE
What is the language name of 100 languages in which Unicoderv3 are pre-trained?

### ISSUE THREAD

**Issue by sunlanchang** [microsoft/Unicoder#6]
I have read Unicoder paper, but I can't find the name of 100 language in which Unicoderv3 are pre-trained. Maybe I miss some important parts, could your please provide the name of the 100 languages? Thanks a lot!

**Comment by Eureka6174** [comment]
It's same as XLM-Roberta. You could find the list at table 6 of https://arxiv.org/pdf/1911.02116.pdf

**Comment by sunlanchang** [comment]
I can see, I'll close this issue. Thank you most sincerely!
