### ISSUE TITLE
Where is the Unicoder model file?

### ISSUE THREAD

**Issue by fake-warrior8** [microsoft/Unicoder#7]
Hi, I can not find where is the Unicoder model.py file? Could you tell me? Thank you very much

**Comment by Eureka6174** [comment]
It's at https://1drv.ms/u/s!Amt8n9AJEyxckUl6e1nXDQmppZFc?e=SE8laa

**Comment by fake-warrior8** [comment]
This is the pytorch file, I'd want to see the source code of Unicoder model. That is, I want to see the implementation of the three pre-training task of Unicoder.

**Comment by Eureka6174** [comment]
Currently we just release the pre-trained model and fine-tuning code.
